# overwrite with env PHOENIX_LOG
log_level = "debug"

[tracing]
# overwrite with env PHOENIX_TRACING
enable = false
# this will log messages level lower than specified into file
# e.g., min_event_level="debug" will log events of "trace" and "debug" to file
# overwrite with env PHOENIX_MIN_TRACING_EVENT
min_event_level = "trace"
# PHOENIX_MAX_TRACING_EVENT, this should be equal or more verbose than min_event_level
max_event_level = "trace"
# overwrite with env PHOENIX_TRACING_SPAN
span_level = "info"
# overwrite with env PHOENIX_TRACING_DIR
output_dir = "/tmp/phoenix-trace"

[profiling]
# overwrite with env PHOENIX_PROFILING_ENABLE_ON_NEW_CLIENT
enable_on_new_client = true
# overwrite with env PHOENIX_PROFILING_DURATION_MS
duration_ms = 1000

# [runtime]
# max_dedicate = 10

[control]
# overwrite with PHOENIX_PREFIX
prefix = "/tmp/phoenix"
# overwrite with PHOENIX_CONTROL
path = "control.sock"

# Modules
[[modules]]
name = "RdmaTransport"
lib_path = "/tmp/phoenix/plugins/libphoenix_transport_rdma_plugin.so"
config_string = '''
prefix = "/tmp/phoenix"
engine_basename = "transport-engine-rdma"
datapath_wq_depth = 32
datapath_cq_depth = 32
command_max_interval_ms = 1000
'''

[[modules]]
name = "TcpTransport"
lib_path = "/tmp/phoenix/plugins/libphoenix_transport_tcp_plugin.so"
config_string = '''
prefix = "/tmp/phoenix"
engine_basename = "transport-engine-tcp"
'''

[[modules]]
name = "Salloc"
lib_path = "/tmp/phoenix/plugins/libphoenix_salloc_plugin.so"
config_string = '''
prefix = "/tmp/phoenix"
engine_basename = "salloc"
'''

[[modules]]
name = "Mrpc"
lib_path = "/tmp/phoenix/plugins/libphoenix_mrpc_plugin.so"
config_string = '''
prefix = "/tmp/phoenix"
engine_basename = "mrpc-engine"
build_cache = "/tmp/phoenix/build-cache"
transport = "Rdma"
'''

[[modules]]
name = "RpcAdapter"
lib_path = "/tmp/phoenix/plugins/libphoenix_rpc_adapter_plugin.so"
config_string = '''
enable_scheduler = false
'''

[[modules]]
name = "TcpRpcAdapter"
lib_path = "/tmp/phoenix/plugins/libphoenix_tcp_rpc_adapter_plugin.so"


# Addons being here
[[addons]]
name = "RateLimit"
lib_path = "/tmp/phoenix/plugins/libphoenix_ratelimit_plugin.so"
config_string = '''
requests_per_sec = 1000
bucket_size = 1000
'''

[[addons]]
name = "Qos"
lib_path = "/tmp/phoenix/plugins/libphoenix_qos_plugin.so"
config_string = '''
latency_budget_microsecs = 10
'''

# Addons being here
[[addons]]
name = "BreakWater"
lib_path = "/tmp/phoenix/plugins/libphoenix_breakwater_plugin.so"
config_string = '''
'''
