[package]
name = "phoenix-api-mrpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phoenix-api = { workspace = true, features = ["mrpc"] }

serde.workspace = true
static_assertions.workspace = true
