[package]
name = "phoenix_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
anyhow.workspace = true
getopts = "0.2.21"
regex = "1.7.1"
toml.workspace = true
serde = { workspace = true, features = ["derive"] }
walkdir = "2.3.2"
shlex = "1.1.0"
semver.workspace = true
