
[package]
name = "phoenix-api-policy-fault"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phoenix-api.workspace = true

serde.workspace = true
itertools.workspace = true
rand.workspace = true
