[package]
name = "rpc_int"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
mrpc-build = { path = "../../mrpc/mrpc-build" }

[dependencies]
mrpc = { path = "../../mrpc" }
prost = { path = "../../3rdparty/prost", features = ["mrpc-frontend"] }

structopt = "0.3.23"
smol = "1.2.5"


[[bin]]
name = "rpc_int_client"
path = "src/client.rs"

[[bin]]
name = "rpc_int_server"
path = "src/server.rs"
