[package]
name = "koala-rpc_adapter_unfused"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib"]

[dependencies]
interface = { path = "../../interface" }
ipc = { path = "../../ipc", features = ["mrpc", "rpc_adapter"] }
koala = { path = "../../koala" }
rdma = { path = "../../rdma", features = ["koala"] }
transport_rdma = { path = "../transport-rdma", package = "koala-transport-rdma" }
mrpc-marshal = { path = "../../mrpc-marshal" } 
salloc = { path = "../salloc", package = "koala-salloc" }
mrpc = { path = "../mrpc", package = "koala-mrpc" }

fnv = "1.0.7"
anyhow = "1.0.58"
tokio = { version = "1.18.2", features = ["sync"] }
thiserror = "1.0.31"
nix = "0.23.0"
futures = "0.3.21"
dashmap = "5.3.4"
spin = "0.9.3"
libloading = "0.7.3"
serde = { version = "1.0.130", features = ["derive"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
fastrand = "1.8.0"
bitvec = "1.0.1"
bincode = "1.3.3"
static_assertions = "1.1.0"