name = "policy/hello-acl/rpc_bench_tput_32b"
description = "Run rpc_bench benchmark"
group = "hello-acl"
timeout_secs = 70

[[worker]]
host = "danyang-06"
bin = "rpc_bench_server"
args = "--port 5002 -l info --transport tcp"

[[worker]]
host = "danyang-04"
bin = "rpc_bench_client2"
args = "--transport tcp -c rdma0.danyang-06 --concurrency 128 --req-size 32 --duration 65 -i 1 --port 5002 -l error"
dependencies = [0]
